name 'zmidar-ffmpeg'
version '0.0.1'
source 'https://github.com/zmidar/puppet-ffmpeg'
author 'zmidar'
license 'MIT License'
summary 'Simple puppet module that installs ffmpeg.'
description 'Simple puppet module that installs ffmpeg.'
project_page 'https://github.com/zmidar/puppet-ffmpeg'
